### ISSUE TITLE
Start, Stop and Restart container instances

### ISSUE THREAD

**Issue by klacol** [Plabick/ACR-Container-Purge-Action#2]
Hi, this is a great wrapper for `acr purge`. I need also to start, stop and restart the instances. Therefore I would need a wrapper for 

```shell
az container start
az container stop
az container restart
```
Is it in the scope of this action to wrap this command, or would it better to make another action?

**Comment by Plabick** [comment]
Thanks for the suggestion! I don't think that is within the scope of this action, but I just made another action to run any Azure CLI command through a GitHub Workflow, which you can find [here](https://github.com/marketplace/actions/azure-cli-wrapper-action). Hope this helps!

**Comment by klacol** [comment]
Hi @Plabick , that ok. Good to keep the focus. Important. Meanwhile I have created the action here: https://github.com/klacol/AzContainerOperations-Action
